import type { Metadata } from "next";
import { Inter, Staatliches } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });
const staatliches = Staatliches({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${staatliches.className} font-inter`}>{children}</body>
    </html>
  );
}
